# Generated by Django 3.0.3 on 2020-10-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField()),
                ('datetime', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
