# Generated by Django 3.0.3 on 2020-10-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='datetime',
            field=models.TextField(),
        ),
    ]
