# Generated by Django 3.0.3 on 2020-10-26 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_auto_20201026_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
